name: Flutter - localization

on:
  push:
    branches: ['*']
   # paths:
  #    - "ux/lib/messages.dart"
  #    - ".github/workflows/localization.yml"
 # pull_request:
  #  branches: [ main ]
 #   paths:
 #     - "ux/lib/messages.dart"
  #    - ".github/workflows/localization.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Dump env
        run: |
          echo ${SOURCE_TAG}
          echo ${SOURCE_BRANCH}
          echo ${SOURCE_TAG}
          echo ${{ GITHUB.ref }}
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'dev' or 'beta'
      # Get dependencies.
      - name: "Get dependencies"
        run: chmod u+x ci/pub_upgrade.sh && ci/pub_upgrade.sh
      - name: "Harvest dart files to populate arb file"
        run: flutter pub run intl_generator:extract_to_arb --output-dir=lib/l10n lib/main.dart lib/pages/home_page.dart lib/pages/html_page.dart lib/pages/list_page.dart lib/pages/choose_page.dart lib/pages/settings_page.dart lib/pages/tracking_page.dart lib/themes/smooth_theme.dart lib/database/dao_product.dart lib/pages/scan/scan_page.dart lib/pages/smooth_it_page.dart lib/database/abstract_dao.dart lib/database/bulk_manager.dart lib/themes/constant_icons.dart lib/themes/theme_provider.dart lib/database/product_query.dart lib/pages/attribute_button.dart lib/database/bulk_deletable.dart lib/database/local_database.dart lib/pages/contribution_page.dart lib/pages/organization_page.dart lib/data_models/product_list.dart lib/database/bulk_insertable.dart lib/pages/text_search_widget.dart lib/data_models/product_extra.dart lib/database/dao_product_list.dart lib/pages/product_copy_helper.dart lib/database/dao_product_extra.dart lib/pages/product/product_page.dart lib/data_models/smooth_it_model.dart lib/pages/user_preferences_page.dart lib/views/label_sneak_peek_view.dart lib/data_models/user_preferences.dart lib/database/group_product_query.dart lib/lists/smooth_product_carousel.dart lib/cards/category_cards/svg_cache.dart lib/database/barcode_product_query.dart lib/cards/data_cards/attribute_card.dart lib/cards/data_cards/attribute_chip.dart lib/data_models/product_preferences.dart lib/data_models/product_query_model.dart lib/data_models/smooth_upload_model.dart lib/database/category_product_query.dart
        working-directory: ./packages/smooth_app
        #packages/smooth_ui_library/lib/widgets/smooth_listTile.dart
        #packages/smooth_ui_library/lib/widgets/smooth_gauge.dart
        #packages/smooth_ui_library/lib/widgets/smooth_card.dart
        #packages/smooth_ui_library/example/lib/main.dart 
        #packages/smooth_ui_library/lib/widgets/smooth_toggle.dart
        #test/widget_test.dart
      - uses: actions/upload-artifact@v2
        with:
          name: translations
          path: packages/smooth_app/lib/l10n/ # or path/to/artifact
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *
          git commit -m "Update localization for ${{ steps.branch_name.outputs.SOURCE_TAG}} version" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: l10n_harvesting
          force: true
